create table if not exists public.contributions (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 60),
  food text not null check (char_length(food) between 2 and 180),
  created_at timestamptz not null default now()
);

alter table public.contributions enable row level security;

grant select, insert on public.contributions to anon;
grant usage, select on sequence public.contributions_id_seq to anon;

create policy "Beiträge sind öffentlich lesbar"
on public.contributions for select
to anon
using (true);

create policy "Gäste dürfen Beiträge anlegen"
on public.contributions for insert
to anon
with check (
  char_length(name) between 2 and 60
  and char_length(food) between 2 and 180
);

alter publication supabase_realtime add table public.contributions;
